import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, float, json, bigint } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Florida Lottery game types */
export const gameTypeEnum = mysqlEnum("gameType", [
  "fantasy_5", "powerball", "mega_millions", "florida_lotto",
  "cash4life", "pick_2", "pick_3", "pick_4", "pick_5"
]);

/** Historical draw results fetched from official sources or entered manually */
export const drawResults = mysqlTable("draw_results", {
  id: int("id").autoincrement().primaryKey(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawDate: bigint("drawDate", { mode: "number" }).notNull(),
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  drawTime: varchar("drawTime", { length: 16 }), // "midday" | "evening" | null
  source: varchar("source", { length: 64 }).default("manual"), // "manual" | "api" | "scraper"
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DrawResult = typeof drawResults.$inferSelect;
export type InsertDrawResult = typeof drawResults.$inferInsert;

/** Predictions generated by the system */
export const predictions = mysqlTable("predictions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  modelName: varchar("modelName", { length: 64 }).notNull(),
  mainNumbers: json("mainNumbers").notNull(),
  specialNumbers: json("specialNumbers"),
  confidenceScore: float("confidenceScore").notNull(),
  metadata: json("metadata"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Prediction = typeof predictions.$inferSelect;
export type InsertPrediction = typeof predictions.$inferInsert;

/** Budget-aware ticket selections (batches of 20 tickets) */
export const ticketSelections = mysqlTable("ticket_selections", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  budget: float("budget").notNull().default(75),
  ticketCount: int("ticketCount").notNull().default(20),
  tickets: json("tickets").notNull(), // Array of { mainNumbers, specialNumbers, modelSource, confidence }
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type TicketSelection = typeof ticketSelections.$inferSelect;
export type InsertTicketSelection = typeof ticketSelections.$inferInsert;

/** Model performance tracking */
export const modelPerformance = mysqlTable("model_performance", {
  id: int("id").autoincrement().primaryKey(),
  modelName: varchar("modelName", { length: 64 }).notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawResultId: int("drawResultId"),
  predictionId: int("predictionId"),
  mainHits: int("mainHits").notNull().default(0),
  specialHits: int("specialHits").notNull().default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ModelPerformance = typeof modelPerformance.$inferSelect;
export type InsertModelPerformance = typeof modelPerformance.$inferInsert;
