import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, float, json, bigint, index, uniqueIndex } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Florida Lottery game types */
export const gameTypeEnum = mysqlEnum("gameType", [
  "fantasy_5", "powerball", "mega_millions", "florida_lotto",
  "cash4life", "pick_2", "pick_3", "pick_4", "pick_5"
]);

/** Historical draw results fetched from official sources or entered manually */
export const drawResults = mysqlTable("draw_results", {
  id: int("id").autoincrement().primaryKey(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawDate: bigint("drawDate", { mode: "number" }).notNull(),
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  drawTime: varchar("drawTime", { length: 16 }), // "midday" | "evening" | null
  source: varchar("source", { length: 64 }).default("manual"), // "manual" | "api" | "scraper"
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DrawResult = typeof drawResults.$inferSelect;
export type InsertDrawResult = typeof drawResults.$inferInsert;

/** Predictions generated by the system */
export const predictions = mysqlTable("predictions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  modelName: varchar("modelName", { length: 64 }).notNull(),
  mainNumbers: json("mainNumbers").notNull(),
  specialNumbers: json("specialNumbers"),
  confidenceScore: float("confidenceScore").notNull(),
  metadata: json("metadata"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Prediction = typeof predictions.$inferSelect;
export type InsertPrediction = typeof predictions.$inferInsert;

/** A single generation run (predictions.generate or tickets.generate) */
export const predictionCandidateBatches = mysqlTable("prediction_candidate_batches", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  source: varchar("source", { length: 64 }).notNull(), // "predictions.generate" | "tickets.generate"
  sumRangeFilterApplied: int("sumRangeFilterApplied").notNull().default(0),
  rankerVersionId: int("rankerVersionId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PredictionCandidateBatch = typeof predictionCandidateBatches.$inferSelect;
export type InsertPredictionCandidateBatch = typeof predictionCandidateBatches.$inferInsert;

/** Each model output stored as a candidate for ranking/auditing */
export const predictionCandidates = mysqlTable("prediction_candidates", {
  id: int("id").autoincrement().primaryKey(),
  batchId: int("batchId").notNull(),
  rankerVersionId: int("rankerVersionId"),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  modelName: varchar("modelName", { length: 64 }).notNull(),
  candidateKey: varchar("candidateKey", { length: 256 }).notNull(), // main|special canonical key
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  baseConfidenceScore: float("baseConfidenceScore").notNull(),
  rankerScore: float("rankerScore").notNull().default(0),
  rankerProbability: float("rankerProbability").notNull().default(0),
  rankPosition: int("rankPosition").notNull().default(0),
  selectedForFinal: int("selectedForFinal").notNull().default(0),
  isInsufficientData: int("isInsufficientData").notNull().default(0),
  metadata: json("metadata"),
  evaluatedDrawResultId: int("evaluatedDrawResultId"),
  rewardScore: float("rewardScore"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PredictionCandidate = typeof predictionCandidates.$inferSelect;
export type InsertPredictionCandidate = typeof predictionCandidates.$inferInsert;

/** Frozen feature vectors used by ranker for each candidate */
export const predictionFeatureSnapshots = mysqlTable("prediction_feature_snapshots", {
  id: int("id").autoincrement().primaryKey(),
  candidateId: int("candidateId").notNull(),
  featureSetVersion: varchar("featureSetVersion", { length: 64 }).notNull(),
  features: json("features").notNull(), // Record<string, number>
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PredictionFeatureSnapshot = typeof predictionFeatureSnapshots.$inferSelect;
export type InsertPredictionFeatureSnapshot = typeof predictionFeatureSnapshots.$inferInsert;

/** Outcome records tied to draw results for each candidate */
export const predictionOutcomes = mysqlTable("prediction_outcomes", {
  id: int("id").autoincrement().primaryKey(),
  candidateId: int("candidateId").notNull(),
  drawResultId: int("drawResultId").notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  rankerVersionId: int("rankerVersionId"),
  mainHits: int("mainHits").notNull().default(0),
  specialHits: int("specialHits").notNull().default(0),
  rewardScore: float("rewardScore").notNull().default(0),
  outcomeTier: varchar("outcomeTier", { length: 32 }).notNull().default("miss"),
  evaluatedAt: timestamp("evaluatedAt").defaultNow().notNull(),
});

export type PredictionOutcome = typeof predictionOutcomes.$inferSelect;
export type InsertPredictionOutcome = typeof predictionOutcomes.$inferInsert;

/** Ranker state/version history (auditable, deterministic coefficients) */
export const rankerVersions = mysqlTable("ranker_versions", {
  id: int("id").autoincrement().primaryKey(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  algorithm: varchar("algorithm", { length: 64 }).notNull().default("online_logistic_regression"),
  featureSetVersion: varchar("featureSetVersion", { length: 64 }).notNull(),
  intercept: float("intercept").notNull().default(0),
  coefficients: json("coefficients").notNull(), // Record<string, number>
  learningRate: float("learningRate").notNull().default(0.05),
  l2Lambda: float("l2Lambda").notNull().default(0.001),
  trainedExamples: int("trainedExamples").notNull().default(0),
  generatedCandidateExamples: int("generatedCandidateExamples").notNull().default(0),
  scannedTicketExamples: int("scannedTicketExamples").notNull().default(0),
  sourceRankerVersionId: int("sourceRankerVersionId"),
  isActive: int("isActive").notNull().default(1),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type RankerVersion = typeof rankerVersions.$inferSelect;
export type InsertRankerVersion = typeof rankerVersions.$inferInsert;

/** Scanned ticket sessions (OCR parse + confirmation lifecycle) */
export const scannedTickets = mysqlTable("scanned_tickets", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawDate: bigint("drawDate", { mode: "number" }).notNull(),
  drawTime: varchar("drawTime", { length: 16 }).notNull(),
  sourceType: varchar("sourceType", { length: 32 }).notNull().default("scanned_ticket"),
  ticketOrigin: varchar("ticketOrigin", { length: 32 }).notNull().default("unknown"), // user_selected | quick_pick | imported_historical | ai_generated_purchased | unknown
  scanStatus: varchar("scanStatus", { length: 32 }).notNull().default("parsed"), // parsed | confirmed | rejected | invalid
  confirmationStatus: varchar("confirmationStatus", { length: 32 }).notNull().default("pending"), // pending | confirmed | rejected
  imageUrl: text("imageUrl"),
  fileKey: varchar("fileKey", { length: 256 }),
  parsedPayload: json("parsedPayload"),
  confirmedPayload: json("confirmedPayload"),
  linkedPurchasedTicketId: int("linkedPurchasedTicketId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => ({
  byUserStatus: index("idx_scanned_tickets_user_status").on(
    table.userId,
    table.confirmationStatus,
    table.scanStatus
  ),
  byGameDraw: index("idx_scanned_tickets_game_draw").on(
    table.gameType,
    table.drawDate,
    table.drawTime
  ),
}));

export type ScannedTicket = typeof scannedTickets.$inferSelect;
export type InsertScannedTicket = typeof scannedTickets.$inferInsert;

/** Parsed rows extracted from a scanned ticket image (one or more plays) */
export const scannedTicketRows = mysqlTable("scanned_ticket_rows", {
  id: int("id").autoincrement().primaryKey(),
  scannedTicketId: int("scannedTicketId").notNull().references(() => scannedTickets.id, { onDelete: "cascade" }),
  rowIndex: int("rowIndex").notNull().default(0),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawDate: bigint("drawDate", { mode: "number" }).notNull(),
  drawTime: varchar("drawTime", { length: 16 }).notNull(),
  parsedMainNumbers: json("parsedMainNumbers").notNull(),
  parsedSpecialNumbers: json("parsedSpecialNumbers"),
  confirmedMainNumbers: json("confirmedMainNumbers"),
  confirmedSpecialNumbers: json("confirmedSpecialNumbers"),
  rowStatus: varchar("rowStatus", { length: 32 }).notNull().default("parsed"), // parsed | confirmed | rejected
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => ({
  byTicketRowIndex: uniqueIndex("uq_scanned_ticket_rows_ticket_row").on(
    table.scannedTicketId,
    table.rowIndex
  ),
  byGameDrawStatus: index("idx_scanned_ticket_rows_game_draw_status").on(
    table.gameType,
    table.drawDate,
    table.drawTime,
    table.rowStatus
  ),
  byScannedTicketId: index("idx_scanned_ticket_rows_ticket_id").on(table.scannedTicketId),
}));

export type ScannedTicketRow = typeof scannedTicketRows.$inferSelect;
export type InsertScannedTicketRow = typeof scannedTicketRows.$inferInsert;

/** Feature snapshots for scanned-ticket rows used as ranker training examples */
export const scannedTicketFeatureSnapshots = mysqlTable("scanned_ticket_feature_snapshots", {
  id: int("id").autoincrement().primaryKey(),
  scannedTicketRowId: int("scannedTicketRowId").notNull().references(() => scannedTicketRows.id, { onDelete: "cascade" }),
  rankerVersionId: int("rankerVersionId").references(() => rankerVersions.id, { onDelete: "set null" }),
  featureSetVersion: varchar("featureSetVersion", { length: 64 }).notNull(),
  features: json("features").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => ({
  byRowFeatureVersion: uniqueIndex("uq_scanned_ticket_feature_row_version").on(
    table.scannedTicketRowId,
    table.featureSetVersion
  ),
  byRowId: index("idx_scanned_ticket_feature_row_id").on(table.scannedTicketRowId),
}));

export type ScannedTicketFeatureSnapshot = typeof scannedTicketFeatureSnapshots.$inferSelect;
export type InsertScannedTicketFeatureSnapshot = typeof scannedTicketFeatureSnapshots.$inferInsert;

/** Outcome rows for scanned tickets after draw-result evaluation */
export const scannedTicketOutcomes = mysqlTable("scanned_ticket_outcomes", {
  id: int("id").autoincrement().primaryKey(),
  scannedTicketId: int("scannedTicketId").notNull().references(() => scannedTickets.id, { onDelete: "cascade" }),
  scannedTicketRowId: int("scannedTicketRowId").notNull().references(() => scannedTicketRows.id, { onDelete: "cascade" }),
  userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  drawResultId: int("drawResultId").notNull().references(() => drawResults.id, { onDelete: "cascade" }),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  sourceSubtype: varchar("sourceSubtype", { length: 48 }).notNull().default("unknown"),
  mainHits: int("mainHits").notNull().default(0),
  specialHits: int("specialHits").notNull().default(0),
  rewardScore: float("rewardScore").notNull().default(0),
  outcomeTier: varchar("outcomeTier", { length: 32 }).notNull().default("miss"),
  trainingWeight: float("trainingWeight").notNull().default(0.35),
  consumedRankerVersionId: int("consumedRankerVersionId").references(() => rankerVersions.id, { onDelete: "set null" }), // legacy alias of global consumed id
  personalConsumedRankerVersionId: int("personalConsumedRankerVersionId"),
  globalConsumedRankerVersionId: int("globalConsumedRankerVersionId").references(() => rankerVersions.id, { onDelete: "set null" }),
  globalPromotionStatus: varchar("globalPromotionStatus", { length: 24 }).notNull().default("pending"), // pending | blocked | promoted
  promotionBlockedReason: text("promotionBlockedReason"),
  evaluatedAt: timestamp("evaluatedAt").defaultNow().notNull(),
}, table => ({
  byRowDrawUnique: uniqueIndex("uq_scanned_ticket_outcome_row_draw").on(
    table.scannedTicketRowId,
    table.drawResultId
  ),
  byUserGamePersonalConsumed: index("idx_scanned_ticket_outcomes_user_game_personal").on(
    table.userId,
    table.gameType,
    table.personalConsumedRankerVersionId
  ),
  byGameGlobalConsumed: index("idx_scanned_ticket_outcomes_game_global_consumed").on(
    table.gameType,
    table.globalConsumedRankerVersionId,
    table.globalPromotionStatus
  ),
  byGameSubtype: index("idx_scanned_ticket_outcomes_game_subtype").on(
    table.gameType,
    table.sourceSubtype
  ),
  byTicketId: index("idx_scanned_ticket_outcomes_ticket_id").on(table.scannedTicketId),
}));

export type ScannedTicketOutcome = typeof scannedTicketOutcomes.$inferSelect;
export type InsertScannedTicketOutcome = typeof scannedTicketOutcomes.$inferInsert;

/** User-scoped personal ranker state/version history */
export const personalRankerVersions = mysqlTable("personal_ranker_versions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  algorithm: varchar("algorithm", { length: 64 }).notNull().default("online_logistic_regression_personal"),
  featureSetVersion: varchar("featureSetVersion", { length: 64 }).notNull(),
  intercept: float("intercept").notNull().default(0),
  coefficients: json("coefficients").notNull(),
  learningRate: float("learningRate").notNull().default(0.03),
  l2Lambda: float("l2Lambda").notNull().default(0.002),
  trainedExamples: int("trainedExamples").notNull().default(0),
  generatedCandidateExamples: int("generatedCandidateExamples").notNull().default(0),
  scannedTicketExamples: int("scannedTicketExamples").notNull().default(0),
  promotedGlobalExamples: int("promotedGlobalExamples").notNull().default(0),
  sourcePersonalRankerVersionId: int("sourcePersonalRankerVersionId"),
  isActive: int("isActive").notNull().default(1),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => ({
  byUserGameActive: index("idx_personal_ranker_versions_user_game_active").on(
    table.userId,
    table.gameType,
    table.isActive,
    table.id
  ),
  byUserGameCreated: index("idx_personal_ranker_versions_user_game_created").on(
    table.userId,
    table.gameType,
    table.createdAt
  ),
}));

export type PersonalRankerVersion = typeof personalRankerVersions.$inferSelect;
export type InsertPersonalRankerVersion = typeof personalRankerVersions.$inferInsert;

/** Audit trail for scanned-signal promotion decisions */
export const personalRankerPromotionAudit = mysqlTable("personal_ranker_promotion_audit", {
  id: int("id").autoincrement().primaryKey(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  personalRankerVersionId: int("personalRankerVersionId").references(() => personalRankerVersions.id, { onDelete: "set null" }),
  promotionStatus: varchar("promotionStatus", { length: 24 }).notNull().default("blocked"), // blocked | promoted
  blockedReason: text("blockedReason"),
  evaluatedOutcomeCount: int("evaluatedOutcomeCount").notNull().default(0),
  promotedOutcomeCount: int("promotedOutcomeCount").notNull().default(0),
  policySnapshot: json("policySnapshot"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => ({
  byGameCreated: index("idx_personal_ranker_promo_game_created").on(
    table.gameType,
    table.createdAt
  ),
  byUserCreated: index("idx_personal_ranker_promo_user_created").on(
    table.userId,
    table.createdAt
  ),
}));

export type PersonalRankerPromotionAudit = typeof personalRankerPromotionAudit.$inferSelect;
export type InsertPersonalRankerPromotionAudit = typeof personalRankerPromotionAudit.$inferInsert;

/** Budget-aware ticket selections (batches of 20 tickets) */
export const ticketSelections = mysqlTable("ticket_selections", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  budget: float("budget").notNull().default(75),
  ticketCount: int("ticketCount").notNull().default(20),
  tickets: json("tickets").notNull(), // Array of { mainNumbers, specialNumbers, modelSource, confidence }
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type TicketSelection = typeof ticketSelections.$inferSelect;
export type InsertTicketSelection = typeof ticketSelections.$inferInsert;

/** Model performance tracking */
export const modelPerformance = mysqlTable("model_performance", {
  id: int("id").autoincrement().primaryKey(),
  modelName: varchar("modelName", { length: 64 }).notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawResultId: int("drawResultId"),
  predictionId: int("predictionId"),
  mainHits: int("mainHits").notNull().default(0),
  specialHits: int("specialHits").notNull().default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ModelPerformance = typeof modelPerformance.$inferSelect;
export type InsertModelPerformance = typeof modelPerformance.$inferInsert;

/** User favorite number combinations */
export const favorites = mysqlTable("favorites", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  label: varchar("label", { length: 128 }),
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  modelSource: varchar("modelSource", { length: 64 }),
  confidence: float("confidence"),
  usageCount: int("usageCount").notNull().default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Favorite = typeof favorites.$inferSelect;
export type InsertFavorite = typeof favorites.$inferInsert;

/** Push notification subscriptions */
export const pushSubscriptions = mysqlTable("push_subscriptions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  endpoint: text("endpoint").notNull(),
  p256dh: text("p256dh").notNull(),
  auth: text("auth").notNull(),
  enabled: int("enabled").notNull().default(1),
  notifyDrawResults: int("notifyDrawResults").notNull().default(1),
  notifyHighAccuracy: int("notifyHighAccuracy").notNull().default(1),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PushSubscription = typeof pushSubscriptions.$inferSelect;
export type InsertPushSubscription = typeof pushSubscriptions.$inferInsert;

/** Uploaded PDF files for historical data import */
export const pdfUploads = mysqlTable("pdf_uploads", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  fileName: varchar("fileName", { length: 256 }).notNull(),
  fileUrl: text("fileUrl").notNull(),
  fileKey: varchar("fileKey", { length: 256 }).notNull(),
  gameType: varchar("gameType", { length: 32 }),
  status: mysqlEnum("status", ["pending", "processing", "completed", "failed"]).default("pending").notNull(),
  drawsExtracted: int("drawsExtracted").default(0),
  errorMessage: text("errorMessage"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PdfUpload = typeof pdfUploads.$inferSelect;
export type InsertPdfUpload = typeof pdfUploads.$inferInsert;

/** Purchased tickets for win/loss tracking */
export const purchasedTickets = mysqlTable("purchased_tickets", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  purchaseDate: bigint("purchaseDate", { mode: "number" }).notNull(),
  drawDate: bigint("drawDate", { mode: "number" }),
  cost: float("cost").notNull(),
  outcome: mysqlEnum("outcome", ["pending", "loss", "win"]).default("pending").notNull(),
  winAmount: float("winAmount").default(0),
  mainHits: int("mainHits").default(0),
  specialHits: int("specialHits").default(0),
  notes: text("notes"),
  modelSource: varchar("modelSource", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PurchasedTicket = typeof purchasedTickets.$inferSelect;
export type InsertPurchasedTicket = typeof purchasedTickets.$inferInsert;
