import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, float, json, bigint } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Florida Lottery game types */
export const gameTypeEnum = mysqlEnum("gameType", [
  "fantasy_5", "powerball", "mega_millions", "florida_lotto",
  "cash4life", "pick_2", "pick_3", "pick_4", "pick_5"
]);

/** Historical draw results fetched from official sources or entered manually */
export const drawResults = mysqlTable("draw_results", {
  id: int("id").autoincrement().primaryKey(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawDate: bigint("drawDate", { mode: "number" }).notNull(),
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  drawTime: varchar("drawTime", { length: 16 }), // "midday" | "evening" | null
  source: varchar("source", { length: 64 }).default("manual"), // "manual" | "api" | "scraper"
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DrawResult = typeof drawResults.$inferSelect;
export type InsertDrawResult = typeof drawResults.$inferInsert;

/** Predictions generated by the system */
export const predictions = mysqlTable("predictions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  modelName: varchar("modelName", { length: 64 }).notNull(),
  mainNumbers: json("mainNumbers").notNull(),
  specialNumbers: json("specialNumbers"),
  confidenceScore: float("confidenceScore").notNull(),
  metadata: json("metadata"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Prediction = typeof predictions.$inferSelect;
export type InsertPrediction = typeof predictions.$inferInsert;

/** Budget-aware ticket selections (batches of 20 tickets) */
export const ticketSelections = mysqlTable("ticket_selections", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  budget: float("budget").notNull().default(75),
  ticketCount: int("ticketCount").notNull().default(20),
  tickets: json("tickets").notNull(), // Array of { mainNumbers, specialNumbers, modelSource, confidence }
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type TicketSelection = typeof ticketSelections.$inferSelect;
export type InsertTicketSelection = typeof ticketSelections.$inferInsert;

/** Model performance tracking */
export const modelPerformance = mysqlTable("model_performance", {
  id: int("id").autoincrement().primaryKey(),
  modelName: varchar("modelName", { length: 64 }).notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  drawResultId: int("drawResultId"),
  predictionId: int("predictionId"),
  mainHits: int("mainHits").notNull().default(0),
  specialHits: int("specialHits").notNull().default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ModelPerformance = typeof modelPerformance.$inferSelect;
export type InsertModelPerformance = typeof modelPerformance.$inferInsert;

/** User favorite number combinations */
export const favorites = mysqlTable("favorites", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  label: varchar("label", { length: 128 }),
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  modelSource: varchar("modelSource", { length: 64 }),
  confidence: float("confidence"),
  usageCount: int("usageCount").notNull().default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Favorite = typeof favorites.$inferSelect;
export type InsertFavorite = typeof favorites.$inferInsert;

/** Push notification subscriptions */
export const pushSubscriptions = mysqlTable("push_subscriptions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  endpoint: text("endpoint").notNull(),
  p256dh: text("p256dh").notNull(),
  auth: text("auth").notNull(),
  enabled: int("enabled").notNull().default(1),
  notifyDrawResults: int("notifyDrawResults").notNull().default(1),
  notifyHighAccuracy: int("notifyHighAccuracy").notNull().default(1),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PushSubscription = typeof pushSubscriptions.$inferSelect;
export type InsertPushSubscription = typeof pushSubscriptions.$inferInsert;

/** Uploaded PDF files for historical data import */
export const pdfUploads = mysqlTable("pdf_uploads", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  fileName: varchar("fileName", { length: 256 }).notNull(),
  fileUrl: text("fileUrl").notNull(),
  fileKey: varchar("fileKey", { length: 256 }).notNull(),
  gameType: varchar("gameType", { length: 32 }),
  status: mysqlEnum("status", ["pending", "processing", "completed", "failed"]).default("pending").notNull(),
  drawsExtracted: int("drawsExtracted").default(0),
  errorMessage: text("errorMessage"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PdfUpload = typeof pdfUploads.$inferSelect;
export type InsertPdfUpload = typeof pdfUploads.$inferInsert;

/** Purchased tickets for win/loss tracking */
export const purchasedTickets = mysqlTable("purchased_tickets", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  mainNumbers: json("mainNumbers").notNull(), // number[]
  specialNumbers: json("specialNumbers"), // number[] | null
  purchaseDate: bigint("purchaseDate", { mode: "number" }).notNull(),
  drawDate: bigint("drawDate", { mode: "number" }),
  cost: float("cost").notNull(),
  outcome: mysqlEnum("outcome", ["pending", "loss", "win"]).default("pending").notNull(),
  winAmount: float("winAmount").default(0),
  mainHits: int("mainHits").default(0),
  specialHits: int("specialHits").default(0),
  notes: text("notes"),
  modelSource: varchar("modelSource", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PurchasedTicket = typeof purchasedTickets.$inferSelect;
export type InsertPurchasedTicket = typeof purchasedTickets.$inferInsert;

/** Personalization metrics for user-specific model/game performance tracking */
export const personalizationMetrics = mysqlTable("personalization_metrics", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  gameType: varchar("gameType", { length: 32 }).notNull(),
  metricType: varchar("metricType", { length: 64 }).notNull(),
  metricValue: float("metricValue").notNull().default(0),
  metadata: json("metadata"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PersonalizationMetric = typeof personalizationMetrics.$inferSelect;
export type InsertPersonalizationMetric = typeof personalizationMetrics.$inferInsert;
