export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET || process.env.SESSION_SECRET || "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmApiUrl: process.env.LLM_API_URL ?? "",
  llmApiKey: process.env.LLM_API_KEY ?? "",
  openAiApiKey: process.env.OPENAI_API_KEY ?? "",
  openAiModel: process.env.OPENAI_OCR_MODEL ?? "gpt-4.1-mini",
  openAiFallbackModel: process.env.OPENAI_OCR_FALLBACK_MODEL ?? "gpt-4.1",
  disableAuth: process.env.DISABLE_AUTH === "true",
  localUploadsDir: process.env.LOCAL_UPLOADS_DIR || "/tmp/uploads",
};
