/**
 * Florida Lottery Official Data Scraper
 * 
 * Parses the official HTML history files from files.floridalottery.com/exptkt/
 * These are static HTML tables generated by Oracle Reports containing complete
 * winning number histories for each game.
 * 
 * File codes (from official FL Lottery website):
 *   Fantasy 5:     ff.htm
 *   Powerball:     pb.htm
 *   Mega Millions: mmil.htm
 *   Florida Lotto:  l6.htm
 *   Cash4Life:     c4l.htm
 *   Pick 5:        p5.htm
 *   Pick 4:        p4.htm
 *   Pick 3:        p3.htm
 *   Pick 2:        p2.htm
 */

import type { GameType } from "@shared/lottery";

const BASE_URL = "https://files.floridalottery.com/exptkt";

/** Map game types to their official file codes (HTML history files).
 *  Cash Pop is handled separately via cashpop-pdf-parser.ts (its source is PDF). */
const FILE_CODES: Record<string, string> = {
  fantasy_5: "ff",
  powerball: "pb",
  mega_millions: "mmil",
  florida_lotto: "l6",
  cash4life: "c4l",
  pick_5: "p5",
  pick_4: "p4",
  pick_3: "p3",
  pick_2: "p2",
};

/** Special number labels in the HTML */
const SPECIAL_LABELS: Record<string, string> = {
  powerball: "PB",
  mega_millions: "MB",
  cash4life: "CB",
};

/** Games that have midday/evening draws */
const MIDDAY_EVENING_GAMES = new Set(["pick_2", "pick_3", "pick_4", "pick_5"]);

export interface ParsedDraw {
  drawDate: string;       // YYYY-MM-DD
  mainNumbers: number[];
  specialNumbers: number[];
  drawTime: string;       // "evening" | "midday"
}

/**
 * Fast extraction of text from <font> tags using indexOf scanning.
 * Much faster than regex on large (10MB+) HTML files.
 */
function extractFontTexts(html: string): string[] {
  const texts: string[] = [];
  let pos = 0;
  while (pos < html.length) {
    const fontStart = html.indexOf("<font", pos);
    if (fontStart === -1) break;
    const gtPos = html.indexOf(">", fontStart);
    if (gtPos === -1) break;
    const fontEnd = html.indexOf("</font>", gtPos);
    if (fontEnd === -1) break;
    let text = html.substring(gtPos + 1, fontEnd)
      .replace(/<[^>]*>/g, "")
      .replace(/&nbsp;/gi, " ")
      .trim();
    if (text) texts.push(text);
    pos = fontEnd + 7;
  }
  return texts;
}

/**
 * Parse a date string from FL Lottery format (MM/DD/YY) to YYYY-MM-DD
 */
function parseDate(dateStr: string): string {
  const parts = dateStr.split("/");
  if (parts.length !== 3) return "";
  const [mm, dd, yy] = parts;
  const year = parseInt(yy, 10);
  const fullYear = year >= 80 ? 1900 + year : 2000 + year;
  return `${fullYear}-${mm.padStart(2, "0")}-${dd.padStart(2, "0")}`;
}

function isDate(text: string): boolean {
  return /^\d{2}\/\d{2}\/\d{2}$/.test(text);
}

function isNumber(text: string): boolean {
  return /^\d+$/.test(text);
}

/** Tokens to skip (page headers that repeat throughout the document) */
function isPageHeader(text: string): boolean {
  return text === "FLORIDA LOTTERY" ||
    text.includes("Winning Numbers History") ||
    text.includes("Winning  Numbers History") ||
    text.includes("Please note") ||
    text.includes("Page") ||
    text === "of" ||
    /^\d+-[A-Z]{3}-\d{4}$/.test(text); // date like "27-AUG-2025"
}

/**
 * Parse draws for Fantasy 5: 5 main numbers, no special
 * Pattern: date, num, -, num, -, num, -, num, -, num
 */
function parseFantasy5(texts: string[]): ParsedDraw[] {
  const draws: ParsedDraw[] = [];
  let i = 0;
  
  while (i < texts.length) {
    if (texts[i] === "FANTASY 5" || isPageHeader(texts[i])) { i++; continue; }
    if (!isDate(texts[i])) { i++; continue; }
    
    const dateStr = parseDate(texts[i]);
    i++;
    
    const numbers: number[] = [];
    while (i < texts.length && numbers.length < 5) {
      if (isDate(texts[i]) || texts[i] === "FANTASY 5") break;
      if (texts[i] === "-" || isPageHeader(texts[i])) { i++; continue; }
      if (isNumber(texts[i])) { numbers.push(parseInt(texts[i], 10)); i++; continue; }
      break;
    }
    
    if (numbers.length === 5 && dateStr) {
      draws.push({ drawDate: dateStr, mainNumbers: numbers, specialNumbers: [], drawTime: "evening" });
    }
  }
  return draws;
}

/**
 * Parse Florida Lotto: 6 main numbers, has LOTTO DP sub-section to skip
 * Pattern: date, num, -, num, -, num, -, num, -, num, -, num
 * Sections: "FLORIDA LOTTO" (main) and "LOTTO DP" (double play, skip)
 */
function parseFloriaLotto(texts: string[]): ParsedDraw[] {
  const draws: ParsedDraw[] = [];
  let i = 0;
  let inLottoDP = false;
  
  while (i < texts.length) {
    if (texts[i] === "FLORIDA LOTTO") { inLottoDP = false; i++; continue; }
    if (texts[i] === "LOTTO" || texts[i] === "LOTTO DP") { inLottoDP = true; i++; continue; }
    if (isPageHeader(texts[i])) { i++; continue; }
    if (!isDate(texts[i])) { i++; continue; }
    
    const dateStr = parseDate(texts[i]);
    i++;
    
    const numbers: number[] = [];
    while (i < texts.length && numbers.length < 6) {
      if (isDate(texts[i]) || texts[i] === "LOTTO" || texts[i] === "LOTTO DP" || texts[i] === "FLORIDA LOTTO") break;
      if (texts[i] === "-" || isPageHeader(texts[i])) { i++; continue; }
      if (isNumber(texts[i])) { numbers.push(parseInt(texts[i], 10)); i++; continue; }
      break;
    }
    
    if (numbers.length === 6 && dateStr && !inLottoDP) {
      draws.push({ drawDate: dateStr, mainNumbers: numbers, specialNumbers: [], drawTime: "evening" });
    }
  }
  return draws;
}

/**
 * Parse Powerball: 5 main + PB special + multiplier
 * Pattern: date, num, -, num, -, num, -, num, -, num, PB, num, X#
 */
function parsePowerball(texts: string[]): ParsedDraw[] {
  const draws: ParsedDraw[] = [];
  let i = 0;
  
  while (i < texts.length) {
    if (texts[i] === "POWER BALL" || isPageHeader(texts[i])) { i++; continue; }
    if (!isDate(texts[i])) { i++; continue; }
    
    const dateStr = parseDate(texts[i]);
    i++;
    
    const mainNumbers: number[] = [];
    while (i < texts.length && mainNumbers.length < 5) {
      if (isDate(texts[i]) || texts[i] === "PB" || texts[i] === "POWER BALL") break;
      if (texts[i] === "-" || isPageHeader(texts[i])) { i++; continue; }
      if (isNumber(texts[i])) { mainNumbers.push(parseInt(texts[i], 10)); i++; continue; }
      break;
    }
    
    const specialNumbers: number[] = [];
    if (i < texts.length && texts[i] === "PB") {
      i++; // skip PB label
      if (i < texts.length && isNumber(texts[i])) {
        specialNumbers.push(parseInt(texts[i], 10));
        i++;
      }
      // Skip multiplier (X2, X3, etc.)
      if (i < texts.length && /^X\d+$/i.test(texts[i])) { i++; }
    }
    
    if (mainNumbers.length === 5 && specialNumbers.length === 1 && dateStr) {
      draws.push({ drawDate: dateStr, mainNumbers, specialNumbers, drawTime: "evening" });
    }
  }
  return draws;
}

/**
 * Parse Mega Millions: 5 main + MB special
 * Pattern: date, num, -, num, -, num, -, num, -, num, MB, num
 */
function parseMegaMillions(texts: string[]): ParsedDraw[] {
  const draws: ParsedDraw[] = [];
  let i = 0;
  
  while (i < texts.length) {
    if (texts[i] === "MEGA MILLIONS" || isPageHeader(texts[i])) { i++; continue; }
    if (!isDate(texts[i])) { i++; continue; }
    
    const dateStr = parseDate(texts[i]);
    i++;
    
    const mainNumbers: number[] = [];
    while (i < texts.length && mainNumbers.length < 5) {
      if (isDate(texts[i]) || texts[i] === "MB" || texts[i] === "MEGA MILLIONS") break;
      if (texts[i] === "-" || isPageHeader(texts[i])) { i++; continue; }
      if (isNumber(texts[i])) { mainNumbers.push(parseInt(texts[i], 10)); i++; continue; }
      break;
    }
    
    const specialNumbers: number[] = [];
    if (i < texts.length && texts[i] === "MB") {
      i++;
      if (i < texts.length && isNumber(texts[i])) {
        specialNumbers.push(parseInt(texts[i], 10));
        i++;
      }
    }
    
    if (mainNumbers.length === 5 && specialNumbers.length === 1 && dateStr) {
      draws.push({ drawDate: dateStr, mainNumbers, specialNumbers, drawTime: "evening" });
    }
  }
  return draws;
}

/**
 * Parse Cash4Life: 5 main + CB special
 * Pattern: date, num, -, num, -, num, -, num, -, num, CB, num
 */
function parseCash4Life(texts: string[]): ParsedDraw[] {
  const draws: ParsedDraw[] = [];
  let i = 0;
  
  while (i < texts.length) {
    if (texts[i] === "CASH4LIFE" || isPageHeader(texts[i])) { i++; continue; }
    if (!isDate(texts[i])) { i++; continue; }
    
    const dateStr = parseDate(texts[i]);
    i++;
    
    const mainNumbers: number[] = [];
    while (i < texts.length && mainNumbers.length < 5) {
      if (isDate(texts[i]) || texts[i] === "CB" || texts[i] === "CASH4LIFE") break;
      if (texts[i] === "-" || isPageHeader(texts[i])) { i++; continue; }
      if (isNumber(texts[i])) { mainNumbers.push(parseInt(texts[i], 10)); i++; continue; }
      break;
    }
    
    const specialNumbers: number[] = [];
    if (i < texts.length && texts[i] === "CB") {
      i++;
      if (i < texts.length && isNumber(texts[i])) {
        specialNumbers.push(parseInt(texts[i], 10));
        i++;
      }
    }
    
    if (mainNumbers.length === 5 && specialNumbers.length === 1 && dateStr) {
      draws.push({ drawDate: dateStr, mainNumbers, specialNumbers, drawTime: "evening" });
    }
  }
  return draws;
}

/**
 * Parse Pick games (2-5 digits, midday/evening)
 * Pattern: date, E/M, digit, -, digit [, -, digit...], FB, num
 * FB = Fireball bonus number (we skip it)
 */
function parsePickGame(texts: string[], digitCount: number, gameName: string): ParsedDraw[] {
  const draws: ParsedDraw[] = [];
  let i = 0;
  
  while (i < texts.length) {
    if (texts[i] === gameName || texts[i].includes("Evening and M:") || texts[i] === "FB" || isPageHeader(texts[i])) {
      // Skip FB labels that appear in header area
      if (texts[i] === "FB" && i + 1 < texts.length && isNumber(texts[i + 1])) {
        i += 2; // skip FB + number
        continue;
      }
      i++;
      continue;
    }
    if (!isDate(texts[i])) { i++; continue; }
    
    const dateStr = parseDate(texts[i]);
    i++;
    
    // Expect E or M
    let drawTime = "evening";
    if (i < texts.length && (texts[i] === "E" || texts[i] === "M")) {
      drawTime = texts[i] === "M" ? "midday" : "evening";
      i++;
    }
    
    const digits: number[] = [];
    while (i < texts.length && digits.length < digitCount) {
      if (isDate(texts[i]) || texts[i] === "E" || texts[i] === "M" || texts[i] === "FB") break;
      if (texts[i] === "-" || isPageHeader(texts[i]) || texts[i] === gameName) { i++; continue; }
      if (isNumber(texts[i]) && parseInt(texts[i], 10) <= 9) {
        digits.push(parseInt(texts[i], 10));
        i++;
        continue;
      }
      break;
    }
    
    // Skip Fireball (FB + number)
    if (i < texts.length && texts[i] === "FB") {
      i++;
      if (i < texts.length && isNumber(texts[i])) { i++; }
    }
    
    if (digits.length === digitCount && dateStr) {
      draws.push({ drawDate: dateStr, mainNumbers: digits, specialNumbers: [], drawTime });
    }
  }
  return draws;
}

/**
 * Fetch and parse historical draw data for a specific game type.
 * Returns parsed draws sorted by date (newest first).
 */
export async function fetchHistoricalDraws(
  gameType: GameType,
  maxDraws: number = 0
): Promise<ParsedDraw[]> {
  // Cash Pop uses a dedicated PDF parser (official source is cp.pdf, not HTML)
  if (gameType === "cash_pop") {
    const { fetchCashPopHistory } = await import("./cashpop-pdf-parser");
    return fetchCashPopHistory(maxDraws);
  }

  const fileCode = FILE_CODES[gameType];
  if (!fileCode) {
    throw new Error(`Unknown game type: ${gameType}`);
  }

  const url = `${BASE_URL}/${fileCode}.htm`;
  
  const response = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (compatible; LottoOracle/2.0)" },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }

  const html = await response.text();
  const texts = extractFontTexts(html);

  if (texts.length < 10) {
    throw new Error(`Insufficient data from ${url} (${texts.length} elements)`);
  }

  let draws: ParsedDraw[];

  switch (gameType) {
    case "fantasy_5":
      draws = parseFantasy5(texts);
      break;
    case "florida_lotto":
      draws = parseFloriaLotto(texts);
      break;
    case "powerball":
      draws = parsePowerball(texts);
      break;
    case "mega_millions":
      draws = parseMegaMillions(texts);
      break;
    case "cash4life":
      draws = parseCash4Life(texts);
      break;
    case "pick_2":
      draws = parsePickGame(texts, 2, "PICK 2");
      break;
    case "pick_3":
      draws = parsePickGame(texts, 3, "PICK 3");
      break;
    case "pick_4":
      draws = parsePickGame(texts, 4, "PICK 4");
      break;
    case "pick_5":
      draws = parsePickGame(texts, 5, "PICK 5");
      break;
    default:
      throw new Error(`Unsupported game type: ${gameType}`);
  }

  // Sort by date descending (newest first)
  draws.sort((a, b) => b.drawDate.localeCompare(a.drawDate));

  // Remove duplicates (same date + same draw time)
  const seen = new Set<string>();
  draws = draws.filter(d => {
    const key = `${d.drawDate}-${d.drawTime}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  if (maxDraws > 0) {
    draws = draws.slice(0, maxDraws);
  }

  return draws;
}

/**
 * Fetch the latest draw results for a specific game (most recent N draws).
 */
export async function fetchLatestDraws(gameType: GameType, count: number = 5): Promise<ParsedDraw[]> {
  return fetchHistoricalDraws(gameType, count);
}

/**
 * Fetch latest draws for ALL supported games.
 */
export async function fetchAllGamesLatest(): Promise<Record<string, ParsedDraw[]>> {
  const results: Record<string, ParsedDraw[]> = {};
  
  for (const gameType of Object.keys(FILE_CODES)) {
    try {
      results[gameType] = await fetchLatestDraws(gameType as GameType);
    } catch (e) {
      console.warn(`[Scraper] Failed to fetch ${gameType}:`, e);
      results[gameType] = [];
    }
  }
  
  return results;
}

// Export for testing
export { extractFontTexts, parseDate, isDate, isNumber, FILE_CODES };
