name: Regenerate Lockfile

on:
  workflow_dispatch:

jobs:
  regenerate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - run: rm -f pnpm-lock.yaml
      - run: pnpm install
      - run: git config --global user.name "GitHub Actions"
      - run: git config --global user.email "actions@github.com"
      - run: git add pnpm-lock.yaml
      - run: git commit -m "Regenerate pnpm-lock.yaml"
      - run: git push